homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('', views.homepage,name='homepage'),
    path('signup', views.signup,name='signup'),
    path('main', views.main,name='main'),
    path('logout',views.logout,name='logout')


]

storyx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import json
import requests
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as django_logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse


def homepage(request):

	if(request.method=='GET'):

		return render(request, 'landing.html')
	else:
		username=request.POST.get("Username")
		password=request.POST.get("Password")

		user=authenticate(username=username,password=password)
		if(user is not None):
			login(request,user)
			return redirect('homepage:main')

		try:
			user = User.objects.get(username=username)
			messages.error(request, "Wrong password.")
			return render(request, 'landing.html')
		except:
			messages.error(request,"Username does not exist.")
			return render(request, 'landing.html')

def signup(request):

	if(request.method == 'GET'):
			return render(request, 'signup.html')
		
	else:
		username= request.POST.get("Username")
		password=request.POST.get("Password")
		try:
			user = User.objects.get(username=username)
			messages.error(request,"Sorry, username is not available.")
			return render(request,'signup.html')
		except:
			user=User.objects.create_user(username=username,password=password)
			messages.success(request,"Sign up successful.")

			
			return redirect(reverse('homepage:homepage'))


@login_required(login_url='homepage:homepage')
def main(request):
	if(request.method=='GET'):
		return render(request,'main.html')

def logout(request):
	django_logout(request)
	return redirect('homepage:homepage')








	    





 

homepage/templates/base.html
{% load static %}
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">

<style type="text/css">
body {
  background: url('/static/543828.jpg') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}

</style>
</head>
			{% include 'navbar.html' %}

<body>
    {% block content %}
    {% endblock %}


</body>
</html>

homepage/templates/landing.html
{% load static %}

<html>
<head>
  <title>Log In - Faraz Abisha's StoryX</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
<style type="text/css">

body {
  background: url('https://c4.wallpaperflare.com/wallpaper/859/973/183/teemusphoto-urban-dystopian-singapore-wallpaper-preview.jpg') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color:black;

}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>


</head>
<body> 

  <div class="font1">
   <div class="container pt-5 fluid" style="text-align: center; color: white">
      <b>Faraz Abisha's Story X</b>
  </div>
</div>
<div class="container pl-2">
<div class="col md-6 pt-5 pl-5" style="color: white">
  <h2><b>Login</b></h2>
  <form method="POST">
    <div class="form-group">
       {% csrf_token %}
       <label>Username:</label>
       <input name="Username" id="Username" type="text" required>
   </div>
   <div class="form-group">
     <label>Password: </label>
     <input name="Password" id="Password" type="password" required>
   </div>
   <div class="form-group">
      <input type="submit" value="Log In" id="log-in" class="btn btn-warning" style="background-color: #426ff5; color: white">

   </div>
   
  </form> 
            {% for i in messages %}
            <h5>{{ i }}</h5>
            {% endfor %}

         <br><br><br><h5>Don't have an account yet?</h5>
         <a href = "{% url 'homepage:signup' %}" id="signbut"><h5 style="color: white"><b><u>Sign up here</u></b></h5></a>
       
</div>
</div>
</div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</div>
</body>
</html>

homepage/templates/main.html
{% load static %}

<html>
<head>
  <title>Faraz Abisha's StoryX</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
<style type="text/css">

body {
  background: url('https://facts.uk/wp-content/uploads/2019/10/interesting-facts-about-Jakarta-1920x1080.jpg') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color:black;

}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>


</head>
<body> 

  <div class="font1">
   <div class="container pt-5 fluid" style="text-align: center; color: white">
      <b>Faraz Abisha's Story X</b>
  </div>
</div>
<div class="container pl-2" >
<div class="col md-6 pt-5 pl-5" style="color: black">



  <h2>Hi, {{ user.username }}!</h2>
  <h4>Have a nice day :)</h4>

  
            {% for i in messages %}
            <h5>{{ i }}</h5>
            {% endfor %}
            <br>
            <a href="{% url 'homepage:logout' %}">
            <input type="submit" value="Log out" id="log-out" class="btn btn-danger">
            </a>
</div>
</div>
</div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</div>
</body>
</html>

homepage/templates/navbar.html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidebar {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidebar a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidebar a:hover {
  color:#ff6443;
}

.sidebar .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
  background-color:#128b86;
  color: white;
  padding: 10px 15px;
  border: none;
}

.openbtn:hover {
  background-color:grey;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
</style>
</head>
<body>

<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <a href="https://story4-trisetio.herokuapp.com">Story4</a>


</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰ Open Sidebar</button>  

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
   
</body>
</html> 

homepage/templates/signup.html
{% load static %}

<html>
<head>
  <title>Sign Up - Faraz Abisha's StoryX</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
<style type="text/css">

body {
  background: url('https://66.media.tumblr.com/b99048340f8caa6561036c89609a1a63/tumblr_px9xvvf4181y40tixo1_400.jpg') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color:black;

}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>


</head>
<body> 

  <div class="font1">
   <div class="container pt-5 fluid" style="text-align: center; color: white">
      <b>Faraz Abisha's Story X</b>
  </div>
</div>
<div class="container pl-2">
<div class="col md-6 pt-5 pl-5" style="color: white">

  <h2><b>Sign Up</b></h2>
  <h5>Register an account now! It's super easy.</h5>

  <form method="POST">
    <div class="form-group">
       {% csrf_token %}
       <label>Username:</label>
       <input name="Username" id="Username" type="text" required>
   </div>
   <div class="form-group">
     <label>Password: </label>
     <input name="Password" id="Password" type="password" required>
   </div>
   <div class="form-group">
      <input type="submit" value="Sign Up" id="sign-up" class="btn btn-warning" style="background-color: #426ff5; color: white">
        {% for i in messages %}
        <br><br><h5>{{ i }}</h5>
        {% endfor %}


   </div>
  </form>

</div>
</div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</div>
</body>
</html>